feat: add support for additional ssl db params
supabase/stripe-sync-engine pull request #100
Opened 2023-12-04 21:49 UTC by nurulhudaapon

## What kind of change does this PR introduce?
Adds a new env variable for adjusting database SSL config.

## What is the current behavior?
Throws error for database using self signed certificate

## What is the new behavior?
Make `ssl.rejectUnauthorized` configurable via the env variable.

## Additional context

![image](https://github.com/supabase/stripe-sync-engine/assets/55424194/8a77e1e1-45cf-42f5-96f0-f6c151a9f88a)

2023-12-05 04:05 UTC, nurulhudaapon commented
@kevcodez Can you take a look at it? We are unable to use our AWS RDS Postgre and blocking us from deploying to prod.

2023-12-13 15:41 UTC, kevcodez requested changes

2023-12-13 15:41 UTC, kevcodez commented on src/routes/webhooks.ts
> +          return reply.send({ received: true, handled: false })
This is a breaking change - for now, simply do not send any unsupported events to the webhook

2023-12-13 15:41 UTC, kevcodez commented on .github/workflows/release.yml
> +          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stripe-sync-engine:latest,${{ secrets.DOCKERHUB_USERNAME }}/stripe-sync-engine:v${{ needs.release.outputs.new-release-version }}
What's the reason for this change? This is also unrelated to the feature

2023-12-13 15:41 UTC, kevcodez commented on src/utils/config.ts
> +    DATABASE_SSL_REJECT_UNAUTHORIZED:
getConfigFromEnv seems to return a string, whereas the typedef says boolean

2023-12-13 15:41 UTC, kevcodez commented on src/utils/PostgresConnection.ts
> +    rejectUnauthorized: config.DATABASE_SSL_REJECT_UNAUTHORIZED,
What's the default setting? In case it's not enabled by default, this is a breaking change (given you set "true" as fallback value)

2023-12-13 16:37 UTC, closed without merging

2023-12-13 16:37 UTC, nurulhudaapon commented
@kevcodez I apologize for killing the time reviewing it, I [found](https://github.com/brianc/node-postgres/tree/master/packages/pg-connection-string#:~:text=sslmode%3Dno%2Dverify%20%2D%20sets%20ssl%20to%20%7B%20rejectUnauthorized%3A%20false%20%7D) that the flag (`ssl.rejectUnauthorized`) can be set through URI query params, and the unrelated changes were mistakenly pushed to the main branch as I was using a custom image for the time being.